{
 "title": "OrderPulse - orders-api",
 "tags": [ "orderpulse" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate by Status",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=\"/orders\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status=~\"5..\",path=\"/orders\"}[1m])) / sum(rate(http_requests_total{path=\"/orders\"}[1m]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "p95 Latency by Pod",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=\"/orders\"}[1m])) by (le, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}