apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: orders-api-canary-health
  namespace: default
spec:
  args:
    - name: canary-hash
  metrics:
    - name: error-rate
      interval: 15s
      count: 3
      successCondition: result[0] < 0.1
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prom-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status=~"5..", path="/orders"}[1m]))
            /
            sum(rate(http_requests_total{path="/orders"}[1m]))
            or on() vector(0)
    - name: p95-latency
      interval: 15s
      count: 3
      successCondition: result[0] < 0.5
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prom-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_seconds_bucket{path="/orders"}[1m])) by (le)
            )
