apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orders-api
  namespace: default
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
      annotations:
        orderpulse.io/restartedAt: "2026-08-05T05:42:34.698688Z"
    spec:
      containers:
        - name: orders-api
          image: ghcr.io/shri-hari27/orderpulse-api:5aa495f
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 20s}
        - analysis:
            templates:
              - templateName: orders-api-canary-health
        - setWeight: 50
        - pause: {duration: 20s}
        - analysis:
            templates:
              - templateName: orders-api-canary-health
        - setWeight: 100
